using SF24_2016_POP2019.Database;
using SF24_2016_POP2019.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace SF24_2016_POP2019.UI
{
    /// <summary>
    /// Interaction logic for PAWindow.xaml
    /// </summary>
    public partial class PAWindow : Window
    {
        ICollectionView view;
        private Korisnik korisnik;
        public PAWindow(Korisnik korisnik)
        {
            InitializeComponent();
            CreateView();
            this.korisnik = korisnik;
        }

        private void CreateView()
        {
            view = CollectionViewSource.GetDefaultView(Data.Instance.Termini);
            view.Filter = PrikazFilter;

            dgProfAsist.IsSynchronizedWithCurrentItem = true;
            dgProfAsist.DataContext = this;
            dgProfAsist.ItemsSource = view;
        }

        private bool PrikazFilter(object obj)
        {
            return !((Termin)obj).Obrisano;
        }

        //Sakrivanje nepotrebnih kolona
        private void DgProfAsist_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgProfAsist.Columns[0].Visibility = System.Windows.Visibility.Hidden;
            dgProfAsist.Columns[5].Visibility = System.Windows.Visibility.Hidden;
            dgProfAsist.Columns[7].Visibility = System.Windows.Visibility.Hidden;
        }

        private void BtnLogout_Click(object sender, RoutedEventArgs e)
        {
            MessageBoxResult result = MessageBox.Show("Da li ste sigurni?", "Izlazak", MessageBoxButton.YesNo);
            if (result == MessageBoxResult.Yes)
            {
                var MainWindow = new MainWindow();
                MainWindow.Show();
                this.Hide();
            };
        }

        private void BtnDodajTermin_Click(object sender, RoutedEventArgs e)
        {
            var noviTermin = new Termin()
            {
                KorisnikId = korisnik.Id,
                Dan = "",
                VremeZauzecaOd = default(DateTime),
                VremeZauzecaDo = default(DateTime),
                TipNastave = Termin.ETipNastave.Predavanje
            };
            var terminProzor = new PADodajTermin(noviTermin, korisnik);
            terminProzor.ShowDialog();
        }

        private void BtnKorisnikInfo_Click(object sender, RoutedEventArgs e)
        {
            PrikazKorisnikaInfo pk = new PrikazKorisnikaInfo(korisnik);
            pk.Show();
        }
    }
}
